name: flutter_portfolio
description: Mohit Kapruwan - Flutter Portfolio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.3
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.2
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/videos/
    - assets/resume/
    - assets/animations/
    - assets/animations/flutter_logo.glb
